apiVersion: skaffold/v4beta5
kind: Config
deploy:
  kubectl:
    remoteManifests:
      - "./infra/k8s/*"
build:
  local:
    push: false
  artifacts:
    - image: ikramhasib007/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"
    - image: ikramhasib007/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"
    - image: ikramhasib007/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"
    - image: ikramhasib007/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"
    - image: ikramhasib007/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"
    - image: ikramhasib007/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"