apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: ticketing
# deploy:
#   kubectl:
#     remoteManifests:
#       - ./infra/k8s/*.yaml
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-390618
  artifacts:
    - image: gcr.io/ticketing-dev-390618/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts|js"
manifests:
  rawYaml:
    - ./infra/k8s/*.yaml
