apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: ticketing
# deploy:
#   kubectl:
#     remoteManifests:
#       - ./infra/k8s/*.yaml
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-390618
  artifacts:
    - image: ikramhasib007/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts|js"
            dest: .
    - image: ikramhasib007/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts|js"
            dest: .
    - image: ikramhasib007/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts|js"
            dest: .
    - image: ikramhasib007/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts|js"
            dest: .
            
manifests:
  rawYaml:
    - ./infra/k8s/*.yaml
