apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: ticketing
build:
  local:
    concurrency: 1
    tryImportMissing: false
    useDockerCLI: false
  artifacts:
    - image: ikramhasib007/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts|js"
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml