apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: ticketing
deploy:
  kubectl:
    remoteManifests:
      - "infra/k8s/auth-depl.yaml"
build:
  local:
    push: false
  artifacts:
    - image: ikramhasib007/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts|js"
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml