name: deploy-manifests
on:
  push:
    branches: [ "main" ]
    paths:
      - 'ticketing/infra/**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ticketing
    steps:
    - uses: actions/checkout@v3
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Save/Connect DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save k8s-ergool-testing
    - name: Applying Kubernetes Manifests
      run: kubectl apply -f './infra/k8s/*.yaml' -f './infra/k8s-prod/*.yaml'
