name: tests-tickets
on:
  push:
    branches: [ "main" ]
    paths:
      - 'ticketing/tickets/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'ticketing/tickets/**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ticketing
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: ./ticketing/tickets/pnpm-lock.yaml
    - name: Install dependencies
      run: cd tickets && pnpm install
    - name: Run tests
      run: cd tickets && pnpm test:ci
