import './globals.css'
import type { Metadata } from 'next'
import { classNames } from '@/utils'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full bg-gray-100">
      <body className={classNames("h-full", inter.className)}>{children}</body>
    </html>
  )
}
